export const MQTT_CONNECT = "MQTT_CONNECT"
export const MQTT_DISCONNECT = "MQTT_DISCONNECT"
export const MQTT_STATUS = "MQTT_STATUS"
export const MQTT_PUBLISH = "MQTT_PUBLISH"
export const MQTT_EVENTS = "MQTT_EVENTS"

export enum MQTT_CONNECTION_STATUS{
    DISCONNECTED,
    CONNECTING,
    CONNECTED,
}