export const INIT_PROVISION = 'INIT_PROVISION';
export const PROVISION_EVENTS = 'PROVISION_EVENTS';

export enum PROVISION_STATUS {
    IDLE,
    PROVISIONING,
    PROVISION_SUCCESS,
    PROVISION_ERROR
}